apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod-args-configmap
spec:
  containers:
  - image: luksa/fortune:args
    name: fortune-args-container
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    args: ["$(INTERVAL)"]
