apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""

# RWO—ReadWriteOnce—Only a single node can mount the volume for reading and writing.
# ROX—ReadOnlyMany—Multiple nodes can mount the volume for reading.
# RWX—ReadWriteMany—Multiple nodes can mount the volume for both reading and writing.
