#If Kubernetes is running in an environment that doesn’t support LoadBalancer services,
#the load balancer will not be provisioned, but the service will
#still behave like a NodePort service.
#That’s because a LoadBalancer service is an extension of a NodePort service.

apiVersion: v1
kind: Service
metadata:
  name: kubia-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kubia
