apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
spec:
  type: NodePort #service type nodeport
  ports:
  - port: 80 #port of service's internal cluster IP
    targetPort: 8080 #target port of backing pods
    nodePort: 30123 #the service will be accessible through 30123 of each of your cluster nodes
  selector:
    app: kubia
