# You don’t need to enclose string values in quotations
# marks (but you must enclose numbers).

apiVersion: v1
kind: Pod
metadata:
  name: fortune2
spec:
  containers:
  - image: luksa/fortune:args
    args: ["2"]
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
