apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd  # parameter passed to provisioner
  zone: europe-west1-b  # parameter passed to provisioner
